### ISSUE TITLE
Why does it require write access to my repos?

### ISSUE THREAD

**Issue by sakgoyal** [NirmalScaria/le-git-graph#12]
basically the question. I understand if it needs read access. but write access should be absolutely not required.

**Comment by NirmalScaria** [comment]
The extension needs only read access and write access is absolutely not required. But GitHub OAuth permission scopes don't have a "repo read" access level. It is either nothing or "repo" access, which comes with both write and read.

If at any moment, GitHub adds a "repo read only" access level, the permission can definitely be changed to that. But until then, this is the only way I guess.

Closing the issue for now. (Thank you for asking, so that it can be clarified for everyone). 😄
