### ISSUE TITLE
Option for PAT based authentication

### ISSUE THREAD

**Issue by Gakk** [NirmalScaria/le-git-graph#33]
Due to security concerns I can not use this on private repositories, as it authenticate directly through your own server.

I suggest you rewrite the plugin to accept a personal access token (PAT), e.g. the same way as the popular _[Refined GitHub](https://github.com/refined-github/refined-github)_ does. If so, a fine grained token could have been supplied, which is more security transparent.

**Comment by Meital-Zicharevich** [comment]
+2

**Comment by NirmalScaria** [comment]
@Gakk @alenkei-pcp @Meital-Zicharevich 
I'm really sorry, I was hospitalised for two weeks, and have been mandated rest for another week. I will fix this issue as soon as I am healthy enough to do it.
Also, thank you so much for being my first sponsor, @Gakk ❤️

**Comment by NirmalScaria** [comment]
Heyy!
I almost completed the custom PAT feature and this happened.

<img width="832" alt="Screenshot 2023-02-14 at 1 57 45 PM" src="https://user-images.githubusercontent.com/46727865/218680452-aea65faa-b940-4123-8159-c7b819749df3.png">

Turns out fine graded PAT doesn't yet support GraphQL. But classic tokens work with GraphQL (I tested). So, the only advantage will be, authentication could be completed without involvement of a backend server and without authorising an OAuth app (which were otherwise essential in the case of GitHub auth).
I'm not sure what to do. Does this make the whole purpose useless or, should the option be given if anyone wants to use their own classic token? The code is mostly ready in any case. :) Looking forward to your suggestions.

@Gakk @alenkei-pcp @Meital-Zicharevich

**Comment by Gakk** [comment]
@NirmalScaria Fantastic to hear you have started implementation 🥳👍

I was not aware of the limitation for fine-grained PAT, but this is no show-stopper as GitHub is working on implementing support:

- **Oct 17, 2022**: _"There are some limits to fine-grained PATs that we'll be addressing in the comming months; (...) Support for GraphQL"_ ([source](https://github.com/community/community/discussions/36441#discussion-4480575))
- **Oct 20, 2022**: _"(...) we'll be adding GraphQL support shortly."_ ([source](https://github.com/community/community/discussions/36441#discussioncomment-3926959))
- **Nov 1, 2022**: _"(...) don't have a great ETA for you right now, but can say it's being worked on actively. Our goal is to have it out by or before March 2023."_ ([source](https://github.com/community/community/discussions/36441#discussioncomment-4042664))

All of these quotes are by GitHub employees on the feedback tracking issue for fine-grained PATs:
https://github.com/community/community/discussions/36441

**Comment by NirmalScaria** [comment]
Heyy! I'm happy to let you know this has been implemented.
The authentication page options now contain a third option, to choose a custom PAT.
And I hope it would work out of the box once GitHub supports Fine Graded PAT for GraphQL.
<img width="1069" alt="Screenshot 2023-02-14 at 3 27 47 PM" src="https://user-images.githubusercontent.com/46727865/218701892-0e15d33d-6870-4266-804f-23a0d698fbed.png">
Thank you so much for the support, @ Gakk
The release could be expected for FireFox today and in a few days for Chrome.

**Comment by Gakk** [comment]
Perfect, will test it when the release for Chrome is available 🚀👍

**Comment by NirmalScaria** [comment]
@Gakk It has been released. Hope you like it. 😌

**Comment by usuallyno** [comment]
Thank you for the update, which are the minimum permission to let the extension work?

**Comment by NirmalScaria** [comment]
@usuallyno  Sorry for the late response. The minimum required permission is public_repo permission.
<img width="637" alt="Screenshot 2023-02-26 at 5 19 44 PM" src="https://user-images.githubusercontent.com/46727865/221408757-c939eede-6b73-4b0e-af35-fdedc9b9ba86.png">
