### ISSUE TITLE
OAuth authorization is not working after it succeeds

### ISSUE THREAD

**Issue by Angelxyj** [NirmalScaria/le-git-graph#77]
**Describe the bug**
OAuth authorization is not working after it succeeds

**Screenshots**
![image](https://github.com/NirmalScaria/le-git-graph/assets/85948645/ec85b417-fb1c-4407-a934-5032620ecd81)

**Version information:**
 - Win 10
 - chrome

**Comment by NirmalScaria** [comment]
Hey,
I just rechecked and verified that all the required services are up. Can you try checking the network requests from the browser? Perhaps something is blocking requests?

**Comment by domportera** [comment]
I have the same issue - here's the error log in firefox

![image](https://github.com/user-attachments/assets/ba546050-ed52-4f2e-8f16-74f70f04bf0e)

**Comment by NirmalScaria** [comment]
Yeah. I was able to reproduce the issue. Firefox version is broken, and chrome version works fine.
Firefox version is not very actively maintained because Firefox has been making too many changes to the way extensions work. And the demand is not that high. I will have a look at it but cannot assure a fix.

**Comment by NirmalScaria** [comment]
@domportera  I have fixed it. :) Try reinstalling the extension. (You might have to refresh the authentication page once if it takes too long)

**Comment by domportera** [comment]
incredible turnaround!! after reinstalling and restarting my browser (and the occasional refresh) it's working, even on organization private repos. thanks so much!
